#!/usr/bin/env bash

# Runs the server without `npm run`.

. "$HOME/shared-bin/richbash.sh"

set -o errexit
set -o nounset

echo "View the app at http://localhost:8999/web" >&2
echo '' >&2

python3 -m http.server --directory . 8999
