// ============================================================
// AUTO-GENERATED — do not edit this file.
// Source: src/web/app.ts
// Regenerate: npm run build  (or any npm run script that builds)
// ============================================================
// src/web/app.ts — chooser + practice front-end. Vanilla ES module.
//
// Browser-only. No runtime imports of project files (the compiled
// dist-web/app.js → web/app.js bundle must be standalone). Type-only
// imports from ../shared/types are erased at compile time.
const STATS_KEY = 'mathpractice.stats';
// ===== utility =====
function $(id) {
    const el = document.getElementById(id);
    if (!el)
        throw new Error(`Missing element: #${id}`);
    return el;
}
function show(id) { $(id).classList.remove('hidden'); }
function hide(id) { $(id).classList.add('hidden'); }
function shuffle(arr) {
    const a = arr.slice();
    for (let i = a.length - 1; i > 0; i -= 1) {
        const j = Math.floor(Math.random() * (i + 1));
        const ai = a[i];
        const aj = a[j];
        a[i] = aj;
        a[j] = ai;
    }
    return a;
}
function loadStats() {
    try {
        const raw = localStorage.getItem(STATS_KEY);
        if (!raw)
            return { version: 1, chapters: {} };
        const data = JSON.parse(raw);
        if (!data.chapters)
            data.chapters = {};
        return data;
    }
    catch {
        return { version: 1, chapters: {} };
    }
}
function saveStats(stats) {
    localStorage.setItem(STATS_KEY, JSON.stringify(stats));
}
function bumpStats(slug, gotIt) {
    const stats = loadStats();
    if (!stats.chapters[slug])
        stats.chapters[slug] = { attempted: 0, gotIt: 0 };
    const entry = stats.chapters[slug];
    entry.attempted += 1;
    if (gotIt)
        entry.gotIt += 1;
    saveStats(stats);
}
function renderMath(el) {
    if (window.renderMathInElement) {
        window.renderMathInElement(el, {
            delimiters: [
                { left: '$$', right: '$$', display: true },
                { left: '$', right: '$', display: false },
            ],
            throwOnError: false,
        });
    }
}
// ===== bank loading =====
async function fetchChapters() {
    const res = await fetch('../chapters.json', { cache: 'no-cache' });
    if (!res.ok)
        throw new Error(`Failed to load chapters.json: ${res.status}`);
    return res.json();
}
async function fetchBank(slug) {
    const res = await fetch(`../bank/${slug}.json`, { cache: 'no-cache' });
    if (!res.ok)
        return { chapter: slug, chapterTitle: '', problems: [] };
    return res.json();
}
// ===== chooser =====
async function renderChooser(chapters) {
    const list = $('chapter-list');
    list.innerHTML = '';
    const stats = loadStats();
    const slugs = Object.keys(chapters);
    for (const slug of slugs) {
        const ch = chapters[slug];
        if (!ch)
            continue;
        const s = stats.chapters[slug];
        const li = document.createElement('li');
        li.dataset['slug'] = slug;
        const name = document.createElement('span');
        name.className = 'ch-name';
        name.textContent = `${slug.toUpperCase()} — ${ch.title}`;
        const stat = document.createElement('span');
        stat.className = 'ch-stats';
        if (!s || s.attempted === 0) {
            stat.innerHTML = `— · <span class='new'>new</span>`;
        }
        else {
            const pct = Math.round((s.gotIt / s.attempted) * 100);
            const cls = pct < 60 ? ' weak' : pct >= 90 ? ' strong' : '';
            stat.innerHTML = `${s.gotIt} / ${s.attempted} · <span class='pct${cls}'>${pct}%</span>`;
        }
        li.appendChild(name);
        li.appendChild(stat);
        li.addEventListener('click', () => { void startSession({ slug, chapters }); });
        list.appendChild(li);
    }
    show('chooser-view');
    hide('practice-view');
}
const session = {
    slug: null,
    chapters: null,
    problems: [],
    index: 0,
    attempted: 0,
    gotIt: 0,
    current: null,
    revealed: false,
};
async function startSession({ slug, chapters }) {
    session.slug = slug;
    session.chapters = chapters;
    session.attempted = 0;
    session.gotIt = 0;
    session.index = 0;
    session.revealed = false;
    if (slug === 'mix') {
        const all = [];
        for (const s of Object.keys(chapters)) {
            const ch = chapters[s];
            if (!ch)
                continue;
            const bank = await fetchBank(s);
            for (const p of bank.problems)
                all.push({ ...p, _chapter: s, _chapterTitle: ch.title });
        }
        session.problems = shuffle(all);
    }
    else {
        const ch = chapters[slug];
        if (!ch)
            throw new Error(`Unknown chapter slug: ${slug}`);
        const bank = await fetchBank(slug);
        session.problems = shuffle(bank.problems.map((p) => ({ ...p, _chapter: slug, _chapterTitle: ch.title })));
    }
    if (session.problems.length === 0) {
        alert('No problems in the bank for this chapter yet. Run npm run generate first.');
        return;
    }
    hide('chooser-view');
    show('practice-view');
    // Push a history entry so the browser Back button returns us to the
    // chooser instead of leaving the app. The popstate listener below
    // handles the UI transition when this entry is popped.
    history.pushState({ view: 'practice' }, '');
    presentProblem();
}
function updateHeader() {
    const title = $('practice-title');
    if (session.slug === 'mix') {
        title.textContent = `Mix · Problem ${session.index + 1} of ${session.problems.length}`;
    }
    else if (session.slug && session.chapters) {
        const ch = session.chapters[session.slug];
        const chTitle = ch?.title ?? '';
        title.textContent = `${session.slug.toUpperCase()} ${chTitle} · Problem ${session.index + 1} of ${session.problems.length}`;
    }
    $('session-tally').textContent = `Session: ${session.gotIt} / ${session.attempted} ✓`;
}
function presentProblem() {
    if (session.index >= session.problems.length) {
        if (confirm("You've worked through all problems in this set. Start over with a fresh shuffle?")) {
            session.problems = shuffle(session.problems);
            session.index = 0;
        }
        else {
            void backToChooser();
            return;
        }
    }
    const current = session.problems[session.index];
    if (!current)
        return;
    session.current = current;
    session.revealed = false;
    $('problem-text').textContent = current.problem;
    $('answer-text').textContent = current.answer;
    $('solution-text').textContent = current.solution;
    $('topic-text').textContent = session.slug === 'mix'
        ? `From ${current._chapter.toUpperCase()} — ${current._chapterTitle} · Topic: ${current.topic}`
        : `Topic: ${current.topic}`;
    hide('answer-block');
    hide('grade-row');
    show('btn-show');
    updateHeader();
    renderMath($('problem-text'));
}
function revealAnswer() {
    if (session.revealed)
        return;
    session.revealed = true;
    hide('btn-show');
    show('answer-block');
    show('grade-row');
    renderMath($('answer-text'));
    renderMath($('solution-text'));
}
function gradeProblem(gotIt) {
    if (!session.revealed)
        return;
    session.attempted += 1;
    if (gotIt)
        session.gotIt += 1;
    if (session.slug && session.slug !== 'mix') {
        bumpStats(session.slug, gotIt);
    }
    else if (session.current) {
        bumpStats(session.current._chapter, gotIt);
    }
    session.index += 1;
    presentProblem();
}
async function backToChooser() {
    // If we have a practice-view history entry, pop it. The popstate
    // listener will then re-render the chooser. Going through history.back()
    // (rather than rendering directly) keeps the URL/history state in sync
    // so the browser Back button does not behave unexpectedly afterwards.
    const state = history.state;
    if (state?.view === 'practice') {
        history.back();
        return;
    }
    const chapters = await fetchChapters();
    await renderChooser(chapters);
}
// ===== boot =====
async function main() {
    const chapters = await fetchChapters();
    await renderChooser(chapters);
    $('btn-mix').addEventListener('click', () => { void startSession({ slug: 'mix', chapters }); });
    $('btn-reset').addEventListener('click', () => {
        if (confirm('Wipe all lifetime stats?')) {
            localStorage.removeItem(STATS_KEY);
            void renderChooser(chapters);
        }
    });
    $('btn-end').addEventListener('click', () => { void backToChooser(); });
    $('btn-show').addEventListener('click', revealAnswer);
    $('btn-got').addEventListener('click', () => gradeProblem(true));
    $('btn-missed').addEventListener('click', () => gradeProblem(false));
    document.addEventListener('keydown', (e) => {
        if ($('practice-view').classList.contains('hidden'))
            return;
        if (e.code === 'Space' && !session.revealed) {
            e.preventDefault();
            revealAnswer();
        }
        else if (session.revealed && (e.key === '1' || e.key.toLowerCase() === 'g'))
            gradeProblem(true);
        else if (session.revealed && (e.key === '2' || e.key.toLowerCase() === 'm'))
            gradeProblem(false);
    });
    // Handle the browser Back button while in the practice view: render
    // the chooser instead of letting the browser leave the app. The
    // history entry pushed by startSession is already consumed by the
    // navigation that triggered this event.
    window.addEventListener('popstate', () => {
        if (!$('practice-view').classList.contains('hidden')) {
            void renderChooser(chapters);
        }
    });
}
main().catch((err) => {
    console.error(err);
    const msg = err instanceof Error ? err.message : String(err);
    alert(`Error loading: ${msg}`);
});
export {};
//# sourceMappingURL=app.js.map